- hosts: all
  become: true
  roles:
    - common
    - zabbix-agent

- hosts: web01
  become: true
  roles:
    - h2o
    - mariadb
    - php
    - zabbix-server
    - grafana-server
    - letsencrypt
