- name: install zabbixrepo
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm

- name: install zabbix-web
  become_user: root
  shell: rpm -ivh --nodeps http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-web-3.0.13-2.el7.noarch.rpm
  ignore_errors: yes

- name: install zabbix-web-mysql
  become_user: root
  shell: rpm -ivh --nodeps http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-web-mysql-3.0.13-2.el7.noarch.rpm
  ignore_errors: yes

- name: install zabbix-web-japanese
  become_user: root
  shell: rpm -ivh --nodeps http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-web-japanese-3.0.13-2.el7.noarch.rpm
  ignore_errors: yes

- name: install zabbix-server-mysql
  yum: name={{ item }} state=present enablerepo=remi-php71 disable_gpg_check=yes
  with_items:
    - zabbix-server-mysql

- name: start zabbix-server
  systemd: name=zabbix-server enabled=yes state=started

- name: copy zabbix_server.conf 
  copy:
    src: "roles/zabbix-server/files/zabbix/{{ item.src }}"
    dest: "/etc/zabbix/{{ item.dest }}"
    backup: no
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}" 
  with_items:
    - { src: zabbix_server.conf, dest: ., owner: root, group: root, mode: 0644 }

- name: copy alertscripts
  copy:
    src: "roles/zabbix-server/files/alertscripts/{{ item.src }}"
    dest: "/usr/lib/zabbix/alertscripts/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0755 
  with_items:
    - { src: slack.sh, dest: . }

  copy:
    src: "roles/zabbix-server/files/externalscripts/{{ item.src }}"
    dest: "/usr/lib/zabbix/externalscripts/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: ssl-cert-check, dest: . }
    - { src: ssl-cert-check.sh, dest: . }
    - { src: timeout, dest: . }
  notify: restart zabbix-server

