- name: create user
  user:
    name: "{{ item.name }}"
    createhome: yes
    password: "{{ item.password | password_hash('sha512') }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state }}"
    remove: "{{ item.remove }}"
  with_items:
  - { shell: '/bin/zsh', groups: 'haha', state: 'present', remove: 'no', name: 'haha', password: 'hahapw' }


- name: add sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "{{ item.match }}"
    line: "{{ item.line }}"
  with_items:
  - { match: 'haha', line: 'haha ALL=(ALL) NOPASSWD: ALL' }

- name: authorized_key for user haha
  authorized_key:
    user: haha
    key: "ssh-rsa  xxxxxxxxxxxxxxxxxxxxxxxxxx"

