- name: install remi epel
  yum: name={{ item }} state=present
  with_items:
    - "{{ PHP_VERSION_EPEL }}"
    - "{{ PHP_VERSION_REMI }}"

- name: php71 install
  yum: name={{ item }} state=present enablerepo=remi,remi-php71
  with_items:
    - php
    - php-gd
    - php-bcmath
    - php-mbstring
    - php-xml
    - php-ldap
    - php-mysqlnd

- name: copy php.ini
  copy:
    src: "roles/php/files/{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: "php.ini", dest: . }
